// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thecoreappnow.Data;

#nullable disable

namespace MyRazorProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250802084756_Theaddedmigrations")]
    partial class Theaddedmigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyRazorProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Knee Sleeves"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Lifting Straps"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "T-Shirts"
                        });
                });

            modelBuilder.Entity("MyRazorProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "SBD Qatar",
                            CategoryId = 1,
                            Description = "High-quality knee sleeves designed to provide support and stability during heavy lifts.",
                            ISBN = "SBD-KS-001",
                            ListPrice = 2500.0,
                            Price = 442.0,
                            Price100 = 399.0,
                            Price50 = 1000.0,
                            Title = "SBD Knee Sleeves"
                        },
                        new
                        {
                            Id = 2,
                            Author = "SBD Qatar",
                            CategoryId = 2,
                            Description = "Durable lifting straps to improve grip and reduce strain during pulling exercises.",
                            ISBN = "SBD-LS-002",
                            ListPrice = 120.0,
                            Price = 110.0,
                            Price100 = 90.0,
                            Price50 = 100.0,
                            Title = "SBD Lifting Straps"
                        },
                        new
                        {
                            Id = 3,
                            Author = "SBD Qatar",
                            CategoryId = 3,
                            Description = "Comfortable and breathable T-shirt designed for performance during training.",
                            ISBN = "SBD-TS-003",
                            ListPrice = 95.0,
                            Price = 85.0,
                            Price100 = 75.0,
                            Price50 = 80.0,
                            Title = "SBD Training T-Shirt - Black"
                        },
                        new
                        {
                            Id = 4,
                            Author = "SBD Qatar",
                            CategoryId = 3,
                            Description = "Limited edition SBD T-shirt in red with premium cotton material.",
                            ISBN = "SBD-TS-004",
                            ListPrice = 110.0,
                            Price = 99.0,
                            Price100 = 89.0,
                            Price50 = 94.0,
                            Title = "SBD T-Shirt - Red Limited Edition"
                        });
                });

            modelBuilder.Entity("MyRazorProject.Models.Product", b =>
                {
                    b.HasOne("MyRazorProject.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
